# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [10]:
my_arr = [None] * 10
print(my_arr)

[None, None, None, None, None, None, None, None, None, None]


3. Create a vector with values ranging from 10 to 49

In [9]:
my_arr2 = np.arange(10,49)
print(my_arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [18]:
print(my_arr2.shape)

(39,)


5. Print the type of the previous array in question 3

In [19]:
print(my_arr2.dtype)

int32


6. Print the numpy version and the configuration


In [23]:
print(np.__version__,np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/miniconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/miniconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/miniconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/miniconda3\\Library\\include']
1.19.2 None


7. Print the dimension of the array in question 3


In [24]:
print(my_arr2.ndim)

1


8. Create a boolean array with all the True values

In [4]:
bool_arr = np.array([1,True,'a'],dtype=bool)
print(bool_arr)

[ True  True  True]


9. Create a two dimensional array

In [6]:
twoD_arr= np.array([[1,2,3],[4,5,6]])
print(twoD_arr)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array

In [7]:
threeD_arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(threeD_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [10]:
rev_arr = my_arr2[::-1]
print(rev_arr)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
my_arr = [None] * 10
my_arr[4] = 1
print(my_arr)

[None, None, None, None, 1, None, None, None, None, None]


13. Create a 3x3 identity matrix

In [9]:
id_mat = np.identity(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float')
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [21]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = arr1 * arr2
print(arr3)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [22]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3 = arr1 == arr2 
print(arr3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [27]:
arr = np.arange(0,10)
arr = arr[arr % 2 == 1]
print(arr)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [39]:
arr = np.arange(0,10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [50]:
arr = np.arange(10)
arr[[5,6,7]] = 0
arr[8:12] = 0
print(arr)

[0 1 2 3 4 0 0 0 0 0]


20. Create a 2d array with 1 on the border and 0 inside

In [52]:
arr= np.array([[1,0,0],[1,0,0]])
print(arr)

[[1 0 0]
 [1 0 0]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [120]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
print(np.where((arr2d >= 5) & (arr2d <= 12) ,1,arr2d))

[[1 2 3]
 [4 1 1]
 [1 1 1]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [146]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [149]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d = arr2d[0]
print(arr2d)

[1 2 3]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [159]:
arr2d = np.arange(9).reshape(3, 3)
print(arr2d)
arr2d = arr2d[1,1]
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [162]:
arr2d = np.arange(9).reshape(3, 3)
print(arr2d)
arr2d = arr2d[2,0:2]
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [167]:
rand = np.random.randn(10, 10)
print(rand)
print(rand.min(), rand.max())

[[-1.64688144 -0.92878939 -0.6543242   0.74259856 -0.07470458 -2.69251736
   0.56117527 -0.33807011  0.17164937  0.20157828]
 [-1.44390776  0.44779575  0.51282378 -1.9543659   0.88747528 -0.39375302
  -0.49078526 -0.62730233  0.09655731 -0.17942897]
 [ 1.42306144  0.61039169 -0.21280578  0.46388585  1.56939362 -0.21464735
  -0.26047439  2.01452537 -0.98612089  0.62614783]
 [-0.88451947 -1.162538   -0.71720442 -0.97040037 -0.24816427 -0.71233073
   0.76868767  0.93042644  1.85938945 -0.68643723]
 [-1.3632133  -0.75202161 -2.32722997  0.1182965  -0.8188668  -0.60303286
   0.76372787  0.63231421  0.55003541  0.31954577]
 [ 0.07658189  0.3203644   0.41975177 -1.67795123  0.44886113 -1.55279639
   0.29200738 -1.55920951  0.95670352  0.81673364]
 [-0.15716732 -1.19236324  0.42370933 -0.5307034   2.19151261 -1.67311295
  -0.50430597 -0.40666457 -0.52319837 -0.61884519]
 [ 0.15697437 -1.67538107  0.24157464  1.64748216 -0.51339086 -0.451053
  -0.10440026 -0.8154953  -1.16574044  0.24737427]
 [

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [171]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
inter = np.intersect1d(a,b)
indexA = []
indexB = []
for x in inter:
    item = np.where(a == x)
    indexA.append(item[0])
    item = np.where(b == x)
    indexB.append(item[0])
    
print("Position in a : ",indexA,"Position in b : ",indexB)
    
    


Position in a :  [array([1, 3], dtype=int64), array([5, 7], dtype=int64)] Position in b :  [array([1, 3], dtype=int64), array([5, 7], dtype=int64)]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names != "Will"])

[[-1.71545609 -0.31696412  0.71020954  1.81374542]
 [-0.25244883 -0.39164619 -0.15404881 -1.7532623 ]
 [ 1.05152503  0.96139131  0.71156563  2.6980072 ]
 [ 1.58493299  1.69879859 -0.44120648 -0.4340457 ]
 [-0.8778475  -3.46683916 -1.84867119 -0.27098272]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[(names != "Will") & (names != "Joe")])

[[-1.90585489 -0.20932518 -0.9312297  -1.45742717]
 [-0.12877755 -1.04622617  0.51923013 -0.05403158]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [47]:
import decimal
arr2d = np.arange(0,15,dtype=np.dtype(decimal.Decimal)).reshape(5,3)
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 10 11]
 [12 13 14]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [49]:
import decimal
arr2d = np.arange(0,16,dtype=np.dtype(decimal.Decimal)).reshape(2,2,4)
print(arr2d)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 10 11]
  [12 13 14 15]]]


33. Swap axes of the array you created in Question 32

In [51]:
import decimal
arr2d = np.arange(0,16,dtype=np.dtype(decimal.Decimal)).reshape(2,2,4)
swapArr = np.swapaxes(arr2d,0,1)
print(swapArr)

[[[0 1 2 3]
  [8 9 10 11]]

 [[4 5 6 7]
  [12 13 14 15]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [62]:
arr = np.arange(10)
sq = np.sqrt(arr)
sq[sq < 0.5] = 0
print(sq)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [78]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
maxArr = [arr1.max(), arr2.max()]
print(maxArr)

[ 1.62315288  0.98479069 -0.87218661  0.03186264 -1.48481501  0.40826655
 -1.47527379 -0.16340647  0.49821386  0.09607917 -0.02874151 -1.79726158] [ 0.46614723  0.63880862  0.80555031  0.08273924 -1.83018568 -0.64612542
 -0.10468976 -0.48042289 -1.01805983 -1.43082031 -0.09471873  0.35603779] [1.6231528831542275, 0.8055503135595471]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq = np.unique(names)
print(sorted(set(uniq)))

['Bob', 'Joe', 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [88]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
arr = np.setdiff1d(a,b)
print(arr)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [94]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[1] = np.array([[10,10,10]])
print(sampleArray)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [95]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [98]:
arr = np.random.randn(20)
print(arr.cumsum())

[ 1.01069051e-03 -1.60956699e+00 -5.80149473e-01  2.42153664e+00
  2.85387405e+00  1.60511063e+00 -2.16841822e-01  2.26117365e+00
  2.53462752e+00  2.95809824e+00  4.19904000e+00  3.92038727e+00
  4.93171816e+00  3.33158184e+00  2.66025058e+00  3.73065961e+00
  3.06771266e+00  8.41255243e-01 -1.09258844e-01  7.70134151e-02]
