# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
array = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
ans = np.reshape(array,(-1,2))
print(ans)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
arr1= np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2= np.array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
ans = np.vstack((arr1,arr2))
print(ans)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [18]:
arr1= np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2= np.array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
ans = np.hstack((arr1,arr2))
print(ans)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [23]:
arr1 = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
ans = arr1.reshape(1,10)
print(ans)

[[0 1 2 3 4 5 6 7 8 9]]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [26]:
arr1 = np.array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])
ans = arr1.reshape(1,15)
print(ans)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [29]:
arr1 = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
ans = arr1.reshape(5,3)
print(ans)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [35]:
arr1 = np.arange(0,25).reshape(5,5)
ans = np.square(arr1) 
print(ans)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [37]:
arr1 = np.arange(0,30).reshape(5,6)
ans = np.mean(arr1) 
print(ans)

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [39]:
arr1 = np.arange(0,30).reshape(5,6)
ans = np.std(arr1) 
print(ans)

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [40]:
arr1 = np.arange(0,30).reshape(5,6)
ans = np.median(arr1) 
print(ans)

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [41]:
arr1 = np.arange(0,30).reshape(5,6)
ans = np.transpose(arr1) 
print(ans)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
arr1 = np.arange(0,16).reshape(4,4)
ans = np.trace(arr1) 
print(ans)

30


## Question:13

### Find the determinant of the previous array in Q12?

In [44]:
arr1 = np.arange(0,16).reshape(4,4)
ans = np.linalg.det(arr1)
print(ans)

-2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [47]:
arr1 = np.arange(0,16).reshape(4,4)
ans = np.percentile(arr1,5)
ans2 = np.percentile(arr1,95)
print("5th perc : ",ans," , 95th perc : ",ans2)

5th perc :  0.75  , 95th perc :  14.25


## Question:15

### How to find if a given array has any null values?

In [50]:
arr1 = np.arange(0,16).reshape(4,4)
ans = np.isnan(arr1).any()
print(ans)

False
